// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYFrNBzQkhZCGxxzq4CQiGvT_85EnzRYY',
    appId: '1:759057795557:web:09400cf3257d5175a3070c',
    messagingSenderId: '759057795557',
    projectId: 'solution-challenge-d6f25',
    authDomain: 'solution-challenge-d6f25.firebaseapp.com',
    storageBucket: 'solution-challenge-d6f25.appspot.com',
    measurementId: 'G-2723VWQGHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1XHYISN0Hk9cEX0TlkL4wVCIfqdPTw5U',
    appId: '1:759057795557:android:190b8725a31a51dfa3070c',
    messagingSenderId: '759057795557',
    projectId: 'solution-challenge-d6f25',
    storageBucket: 'solution-challenge-d6f25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWdFq6lFh_KqmbACNBJdkh4oT43SdSvuU',
    appId: '1:759057795557:ios:b19d273ff374ecd0a3070c',
    messagingSenderId: '759057795557',
    projectId: 'solution-challenge-d6f25',
    storageBucket: 'solution-challenge-d6f25.appspot.com',
    iosClientId: '759057795557-sgccbr1oqd8ukl97kdq1obv583pum6j4.apps.googleusercontent.com',
    iosBundleId: 'com.example.threatAwareness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWdFq6lFh_KqmbACNBJdkh4oT43SdSvuU',
    appId: '1:759057795557:ios:b19d273ff374ecd0a3070c',
    messagingSenderId: '759057795557',
    projectId: 'solution-challenge-d6f25',
    storageBucket: 'solution-challenge-d6f25.appspot.com',
    iosClientId: '759057795557-sgccbr1oqd8ukl97kdq1obv583pum6j4.apps.googleusercontent.com',
    iosBundleId: 'com.example.threatAwareness',
  );
}
